/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BenefitItem: typeof import('./src/components/BenefitItem.vue')['default']
    BenefitItems: typeof import('./src/components/BenefitItems.vue')['default']
    BenefitsSection: typeof import('./src/components/BenefitsSection.vue')['default']
    Button: typeof import('primevue/button')['default']
    CallToAction: typeof import('./src/components/CallToAction.vue')['default']
    CallToActionSection: typeof import('./src/components/CallToActionSection.vue')['default']
    Card: typeof import('primevue/card')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    ContentSection: typeof import('./src/components/ContentSection.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DisclaimerSection: typeof import('./src/components/DisclaimerSection.vue')['default']
    ExerciseConclusion: typeof import('./src/components/ExerciseConclusion.vue')['default']
    ExerciseWarning: typeof import('./src/components/ExerciseWarning.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    GettingStartedTips: typeof import('./src/components/GettingStartedTips.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Highlight: typeof import('./src/components/Highlight.vue')['default']
    HighLight: typeof import('./src/components/High-light.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    IntroductionSection: typeof import('./src/components/IntroductionSection.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuTemplate: typeof import('./src/components/MenuTemplate.vue')['default']
    Message: typeof import('primevue/message')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    SiteNavigation: typeof import('./src/components/SiteNavigation.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
    VideoSection: typeof import('./src/components/VideoSection.vue')['default']
    VisualElement: typeof import('./src/components/VisualElement.vue')['default']
  }
}
